# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from chronicle.proto import chronicle_pb2 as chronicle_dot_proto_dot_chronicle__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chronicle/proto/chronicle_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChronicleStub:
    """---------------------------------------------------------------------------
    The service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartWorkflow = channel.unary_unary(
                '/chronicle.Chronicle/StartWorkflow',
                request_serializer=chronicle_dot_proto_dot_chronicle__pb2.StartWorkflowRequest.SerializeToString,
                response_deserializer=chronicle_dot_proto_dot_chronicle__pb2.StartWorkflowResponse.FromString,
                _registered_method=True)
        self.GetWorkflowResult = channel.unary_unary(
                '/chronicle.Chronicle/GetWorkflowResult',
                request_serializer=chronicle_dot_proto_dot_chronicle__pb2.GetWorkflowResultRequest.SerializeToString,
                response_deserializer=chronicle_dot_proto_dot_chronicle__pb2.GetWorkflowResultResponse.FromString,
                _registered_method=True)
        self.PollActivityTask = channel.unary_unary(
                '/chronicle.Chronicle/PollActivityTask',
                request_serializer=chronicle_dot_proto_dot_chronicle__pb2.PollActivityTaskRequest.SerializeToString,
                response_deserializer=chronicle_dot_proto_dot_chronicle__pb2.PollActivityTaskResponse.FromString,
                _registered_method=True)
        self.ReportActivityResult = channel.unary_unary(
                '/chronicle.Chronicle/ReportActivityResult',
                request_serializer=chronicle_dot_proto_dot_chronicle__pb2.ReportActivityResultRequest.SerializeToString,
                response_deserializer=chronicle_dot_proto_dot_chronicle__pb2.ReportActivityResultResponse.FromString,
                _registered_method=True)
        self.ReleaseActivityTask = channel.unary_unary(
                '/chronicle.Chronicle/ReleaseActivityTask',
                request_serializer=chronicle_dot_proto_dot_chronicle__pb2.ReleaseActivityTaskRequest.SerializeToString,
                response_deserializer=chronicle_dot_proto_dot_chronicle__pb2.ReleaseActivityTaskResponse.FromString,
                _registered_method=True)


class ChronicleServicer:
    """---------------------------------------------------------------------------
    The service
    ---------------------------------------------------------------------------

    """

    def StartWorkflow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkflowResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PollActivityTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportActivityResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseActivityTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChronicleServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartWorkflow': grpc.unary_unary_rpc_method_handler(
                    servicer.StartWorkflow,
                    request_deserializer=chronicle_dot_proto_dot_chronicle__pb2.StartWorkflowRequest.FromString,
                    response_serializer=chronicle_dot_proto_dot_chronicle__pb2.StartWorkflowResponse.SerializeToString,
            ),
            'GetWorkflowResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkflowResult,
                    request_deserializer=chronicle_dot_proto_dot_chronicle__pb2.GetWorkflowResultRequest.FromString,
                    response_serializer=chronicle_dot_proto_dot_chronicle__pb2.GetWorkflowResultResponse.SerializeToString,
            ),
            'PollActivityTask': grpc.unary_unary_rpc_method_handler(
                    servicer.PollActivityTask,
                    request_deserializer=chronicle_dot_proto_dot_chronicle__pb2.PollActivityTaskRequest.FromString,
                    response_serializer=chronicle_dot_proto_dot_chronicle__pb2.PollActivityTaskResponse.SerializeToString,
            ),
            'ReportActivityResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportActivityResult,
                    request_deserializer=chronicle_dot_proto_dot_chronicle__pb2.ReportActivityResultRequest.FromString,
                    response_serializer=chronicle_dot_proto_dot_chronicle__pb2.ReportActivityResultResponse.SerializeToString,
            ),
            'ReleaseActivityTask': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseActivityTask,
                    request_deserializer=chronicle_dot_proto_dot_chronicle__pb2.ReleaseActivityTaskRequest.FromString,
                    response_serializer=chronicle_dot_proto_dot_chronicle__pb2.ReleaseActivityTaskResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chronicle.Chronicle', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chronicle.Chronicle', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Chronicle:
    """---------------------------------------------------------------------------
    The service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def StartWorkflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronicle.Chronicle/StartWorkflow',
            chronicle_dot_proto_dot_chronicle__pb2.StartWorkflowRequest.SerializeToString,
            chronicle_dot_proto_dot_chronicle__pb2.StartWorkflowResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkflowResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronicle.Chronicle/GetWorkflowResult',
            chronicle_dot_proto_dot_chronicle__pb2.GetWorkflowResultRequest.SerializeToString,
            chronicle_dot_proto_dot_chronicle__pb2.GetWorkflowResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PollActivityTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronicle.Chronicle/PollActivityTask',
            chronicle_dot_proto_dot_chronicle__pb2.PollActivityTaskRequest.SerializeToString,
            chronicle_dot_proto_dot_chronicle__pb2.PollActivityTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportActivityResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronicle.Chronicle/ReportActivityResult',
            chronicle_dot_proto_dot_chronicle__pb2.ReportActivityResultRequest.SerializeToString,
            chronicle_dot_proto_dot_chronicle__pb2.ReportActivityResultResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseActivityTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chronicle.Chronicle/ReleaseActivityTask',
            chronicle_dot_proto_dot_chronicle__pb2.ReleaseActivityTaskRequest.SerializeToString,
            chronicle_dot_proto_dot_chronicle__pb2.ReleaseActivityTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
