# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chronicle/proto/chronicle.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chronicle/proto/chronicle.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x63hronicle/proto/chronicle.proto\x12\tchronicle\"U\n\x14StartWorkflowRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12\x15\n\rworkflow_name\x18\x02 \x01(\t\x12\x11\n\targs_json\x18\x03 \x01(\t\"\x17\n\x15StartWorkflowResponse\"/\n\x18GetWorkflowResultRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\"\xca\x01\n\x19GetWorkflowResultResponse\x12;\n\x06status\x18\x01 \x01(\x0e\x32+.chronicle.GetWorkflowResultResponse.Status\x12\x13\n\x0bresult_json\x18\x02 \x01(\t\x12\x12\n\nerror_type\x18\x03 \x01(\t\x12\x15\n\rerror_message\x18\x04 \x01(\t\"0\n\x06Status\x12\x0b\n\x07RUNNING\x10\x00\x12\r\n\tCOMPLETED\x10\x01\x12\n\n\x06\x46\x41ILED\x10\x02\"-\n\x17PollActivityTaskRequest\x12\x12\n\ntask_queue\x18\x01 \x01(\t\"w\n\x0c\x41\x63tivityTask\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x13\n\x0bworkflow_id\x18\x02 \x01(\t\x12\x15\n\ractivity_name\x18\x03 \x01(\t\x12\x11\n\targs_json\x18\x04 \x01(\t\x12\x17\n\x0fidempotency_key\x18\x05 \x01(\t\"O\n\x18PollActivityTaskResponse\x12*\n\x04task\x18\x01 \x01(\x0b\x32\x17.chronicle.ActivityTaskH\x00\x88\x01\x01\x42\x07\n\x05_task\"\x7f\n\x1bReportActivityResultRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\t\x12\x15\n\x0bresult_json\x18\x02 \x01(\tH\x00\x12-\n\x07\x66\x61ilure\x18\x03 \x01(\x0b\x32\x1a.chronicle.ActivityFailureH\x00\x42\t\n\x07outcome\"<\n\x0f\x41\x63tivityFailure\x12\x12\n\nerror_type\x18\x01 \x01(\t\x12\x15\n\rerror_message\x18\x02 \x01(\t\"\x1e\n\x1cReportActivityResultResponse2\x85\x03\n\tChronicle\x12R\n\rStartWorkflow\x12\x1f.chronicle.StartWorkflowRequest\x1a .chronicle.StartWorkflowResponse\x12^\n\x11GetWorkflowResult\x12#.chronicle.GetWorkflowResultRequest\x1a$.chronicle.GetWorkflowResultResponse\x12[\n\x10PollActivityTask\x12\".chronicle.PollActivityTaskRequest\x1a#.chronicle.PollActivityTaskResponse\x12g\n\x14ReportActivityResult\x12&.chronicle.ReportActivityResultRequest\x1a\'.chronicle.ReportActivityResultResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chronicle.proto.chronicle_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STARTWORKFLOWREQUEST']._serialized_start=46
  _globals['_STARTWORKFLOWREQUEST']._serialized_end=131
  _globals['_STARTWORKFLOWRESPONSE']._serialized_start=133
  _globals['_STARTWORKFLOWRESPONSE']._serialized_end=156
  _globals['_GETWORKFLOWRESULTREQUEST']._serialized_start=158
  _globals['_GETWORKFLOWRESULTREQUEST']._serialized_end=205
  _globals['_GETWORKFLOWRESULTRESPONSE']._serialized_start=208
  _globals['_GETWORKFLOWRESULTRESPONSE']._serialized_end=410
  _globals['_GETWORKFLOWRESULTRESPONSE_STATUS']._serialized_start=362
  _globals['_GETWORKFLOWRESULTRESPONSE_STATUS']._serialized_end=410
  _globals['_POLLACTIVITYTASKREQUEST']._serialized_start=412
  _globals['_POLLACTIVITYTASKREQUEST']._serialized_end=457
  _globals['_ACTIVITYTASK']._serialized_start=459
  _globals['_ACTIVITYTASK']._serialized_end=578
  _globals['_POLLACTIVITYTASKRESPONSE']._serialized_start=580
  _globals['_POLLACTIVITYTASKRESPONSE']._serialized_end=659
  _globals['_REPORTACTIVITYRESULTREQUEST']._serialized_start=661
  _globals['_REPORTACTIVITYRESULTREQUEST']._serialized_end=788
  _globals['_ACTIVITYFAILURE']._serialized_start=790
  _globals['_ACTIVITYFAILURE']._serialized_end=850
  _globals['_REPORTACTIVITYRESULTRESPONSE']._serialized_start=852
  _globals['_REPORTACTIVITYRESULTRESPONSE']._serialized_end=882
  _globals['_CHRONICLE']._serialized_start=885
  _globals['_CHRONICLE']._serialized_end=1274
# @@protoc_insertion_point(module_scope)
